In [1]:
import torch

In [9]:
x = torch.tensor([[[1,2,3], [4,5,6]]])
print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.device)
print(x.requires_grad)
print(x.grad)
print(x.grad_fn)


tensor([[[1, 2, 3],
         [4, 5, 6]]])
torch.Size([1, 2, 3])
3
torch.int64
cpu
False
None
None


In [11]:
print(x.squeeze())
print(x.squeeze(0))
print(x.squeeze(-1))
print(x.unsqueeze(0))
print(x.unsqueeze(1))
print(x.unsqueeze(-1))


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[1, 2, 3],
         [4, 5, 6]]])
tensor([[[[1, 2, 3],
          [4, 5, 6]]]])
tensor([[[[1, 2, 3],
          [4, 5, 6]]]])
tensor([[[[1],
          [2],
          [3]],

         [[4],
          [5],
          [6]]]])


In [13]:
r = torch.randn(10, 10)
print(r)
print(r.shape)
print(r.ndim)
print(r.dtype)
print(r.device)
print(r.requires_grad)
print(r.grad)
print(r.unsqueeze(0))

tensor([[-0.6104,  1.6067,  0.5975, -0.4220, -0.6210, -1.2866,  0.5662, -0.3288,
         -1.2979, -0.5033],
        [ 1.0270,  1.7484, -1.1488, -0.3299,  0.3731, -0.2916,  1.8251,  0.8657,
          0.4073,  0.5711],
        [-0.8719, -1.3649,  0.8948, -0.4549, -0.9155,  1.5062,  0.4358, -0.2160,
         -0.0799,  0.3884],
        [-0.0492,  0.1521, -0.3130,  0.7340,  1.4248,  0.5763,  0.7347,  2.4385,
         -0.1569, -2.0008],
        [ 0.7302, -0.6924,  1.1929, -0.8076,  0.8361,  0.1709, -1.2438, -0.3686,
         -0.3449,  0.5323],
        [-0.7860, -0.3540,  1.6756,  1.0632,  0.4304,  0.6685,  0.8279, -0.2304,
         -0.7146, -0.7981],
        [ 1.4953,  0.3311,  2.1741, -1.0376, -0.6110,  0.9008,  2.1201,  0.6185,
         -1.1171, -0.6907],
        [ 1.0337,  1.2914, -1.6962, -0.9669, -0.3052, -0.2623, -0.9276,  0.9941,
         -0.8583, -0.1828],
        [ 1.0775, -0.8360, -0.4744, -0.9538, -1.0502,  0.1790,  1.1643, -1.1968,
          0.2713, -0.8154],
        [ 1.1733,  